/* eslint-disable */
// Generated by Vunora. Do not edit by hand; the import rewrites this file.
// Auto-generated by Vunora site importer. Safe to edit, but regeneration
// will overwrite. Move customizations to a sibling file if you need to keep them.
// Renders Vunora's two site-wide custom-code slots. Both belong inside
// <body>: React cannot emit arbitrary markup inside <head> (a tag manager
// ships a <script> AND a <noscript><iframe>), so the head slot renders as
// the FIRST child of <body> — the placement Next's own @next/third-parties
// GoogleTagManager uses — and the body-end slot as the last.
import { VunoraRuntime } from './vunora-runtime'

// Baked in by the importer; NEXT_PUBLIC_VUNORA_* env vars override for staging.
const BAKED_API_URL = null
// Site-scoped publishable read key, sent as `x-vunora-key`. Safe to ship:
// read-only, this site only, revocable. Without one the slots render empty —
// re-run the import, or approve the key-refresh pull request Vunora offers
// after a rotation, to bake a current key.
const BAKED_PUBLISHABLE_KEY = "vnr_pk_4e5e83bc4d0ce54dc23d5ce4761008cf063a617868c5d718"
const API_URL = process.env.NEXT_PUBLIC_VUNORA_API_URL ?? BAKED_API_URL ?? undefined
const VUNORA_KEY = process.env.NEXT_PUBLIC_VUNORA_KEY ?? BAKED_PUBLISHABLE_KEY ?? undefined

// ── Site-wide custom code ────────────────────────────────────────────────
// Two site-wide snippet slots (head + body-end) authored in Vunora's
// dashboard, delivered by GET /api/vunora/site-code — always 200 with
// { head, bodyEnd }, empty strings when nothing is set. Any failure yields
// the same empty pair; a broken snippet fetch must never break a page.
export type VunoraSiteCodeSlots = { head: string; bodyEnd: string }

export async function fetchSiteCode(): Promise<VunoraSiteCodeSlots> {
  const empty: VunoraSiteCodeSlots = { head: '', bodyEnd: '' }
  if (!API_URL || !VUNORA_KEY) return empty
  try {
    const res = await fetch(`${API_URL}/api/vunora/site-code`, {
      headers: { Accept: 'application/json', 'x-vunora-key': VUNORA_KEY },
      next: { revalidate: 60, tags: ['site-code'] },
    })
    if (!res.ok) return empty
    const json = (await res.json()) as { head?: unknown; bodyEnd?: unknown }
    return {
      head: typeof json.head === 'string' ? json.head : '',
      bodyEnd: typeof json.bodyEnd === 'string' ? json.bodyEnd : '',
    }
  } catch {
    return empty
  }
}

export async function VunoraSiteCode({ slot }: { slot: 'head' | 'body-end' }) {
  const code = await fetchSiteCode()
  const value = slot === 'head' ? code.head : code.bodyEnd
  // Vunora's browser runtime: a client module the server render mounts once
  // so the generated helper reaches the browser bundle. Read before the empty
  // check, because a site with no custom code still needs its analytics, live
  // preview and click-to-edit.
  const runtime = slot === 'head' ? <VunoraRuntime /> : null
  if (!value) return runtime
  return (
    <>
      {runtime}
      <div
      data-vunora-site-code={slot}
      // display: contents so the wrapper adds no box of its own — the
      // snippet behaves as if it were a direct child of <body>.
      style={{ display: 'contents' }}
      dangerouslySetInnerHTML={{ __html: value }}
    />
    </>
  )
}
