/* eslint-disable */
// Generated by Vunora. Do not edit by hand; the import rewrites this file.
// Auto-generated by Vunora site importer. Safe to edit, but regeneration
// will overwrite. Move customizations to a sibling file if you need to keep them.
'use client'

// Vunora browser runtime. Importing the generated helper from a client module
// is what puts it in the browser bundle, where its module scope starts the
// analytics tracker, mirrors the visitor id into a first-party cookie, polls
// for published changes, listens for live-preview messages and boots the
// click-to-edit overlay. A Server Component's imports never reach the browser,
// so without this file none of that runs on server-rendered pages.
import '../lib/vunora'

export function VunoraRuntime(): null {
  return null
}
