/* eslint-disable */
// Generated by Vunora. Do not edit by hand; the import rewrites this file.
// Auto-generated by Vunora site importer. Receives Vunora's publish pushes
// (POST { paths: string[] } with Authorization: Bearer <secret>) and
// revalidates the affected paths and cache tags, so published edits go live
// without a redeploy. Requires the server-side VUNORA_REVALIDATE_SECRET env
// var; requests are rejected 401 until it is set.
import { revalidatePath, revalidateTag } from 'next/cache'

// Only POST is exported, so Next answers every other method with its own 405.
// Vunora's smoke test reads the status codes: 404 = this route is missing,
// 405 = method mismatch, 401 = secret mismatch. Keep those semantics.

// revalidateTag's second parameter does not exist in Next 15 and is REQUIRED
// in Next 16, so no single typed call compiles on both — and this repo can be
// upgraded across that boundary long after the import ran. The call goes
// through this one narrowed reference instead: Next 15 ignores the extra
// argument at runtime, Next 16 reads it, and neither major fails the build.
const revalidateCacheTag = revalidateTag as unknown as (
  tag: string,
  profile?: { expire?: number }
) => void

// Constant-time comparison over UTF-8 bytes. node:crypto's timingSafeEqual is
// deliberately not used: it needs @types/node, which an App Router repo need
// not declare, and the Buffer it takes stopped satisfying its own parameter
// type on repos resolving an older copy. TextEncoder is a web standard the
// Node, edge and browser runtimes Next targets all provide.
function secretMatches(presented: string, expected: string): boolean {
  const a = new TextEncoder().encode(presented)
  const b = new TextEncoder().encode(expected)
  // Unequal lengths cannot be compared byte-for-byte. The early return leaks
  // only the secret's length, never its content.
  if (a.length !== b.length) return false
  let diff = 0
  for (let i = 0; i < a.length; i++) diff |= (a[i] ?? 0) ^ (b[i] ?? 0)
  return diff === 0
}

function authorized(header: string | null): boolean {
  const secret = process.env.VUNORA_REVALIDATE_SECRET
  if (!secret || !header || !header.startsWith('Bearer ')) return false
  return secretMatches(header.slice('Bearer '.length), secret)
}

export async function POST(req: Request) {
  if (!authorized(req.headers.get('authorization'))) {
    return Response.json({ ok: false }, { status: 401 })
  }
  const body = (await req.json().catch(() => ({}))) as {
    paths?: string[]
    path?: string
    tag?: string
    tags?: string[]
  }
  const paths = [
    ...(Array.isArray(body.paths) ? body.paths : []),
    ...(typeof body.path === 'string' ? [body.path] : []),
  ].filter((p): p is string => typeof p === 'string' && p.length > 0)
  const explicitTags = [
    ...(Array.isArray(body.tags) ? body.tags : []),
    ...(typeof body.tag === 'string' ? [body.tag] : []),
  ].filter((t): t is string => typeof t === 'string' && t.length > 0)

  let tagCount = 0
  for (const p of paths) {
    revalidatePath(p)
    // Mirror the catch-all's slug derivation ('/' is the 'home' document,
    // '/a/b' is slug 'a/b'): the generated helper caches each page fetch
    // under `page:<slug>`, so busting the tag refreshes the data cache too.
    const slug = p.replace(/^\/+/, '') || 'home'
    revalidateCacheTag(`page:${slug}`, { expire: 0 })
    tagCount++
  }
  for (const t of explicitTags) {
    revalidateCacheTag(t, { expire: 0 })
    tagCount++
  }
  return Response.json({ revalidated: true, paths: paths.length, tags: tagCount })
}
