/* eslint-disable */
// Generated by Vunora. Do not edit by hand; the import rewrites this file.
// Auto-generated by Vunora site importer. Resolves any slug to a CMS Page
// document and renders its layout. File-based routes for specific slugs in
// this repo continue to win over this catch-all.
'use client'

import { RenderBlocks, type VunoraPage } from '../../lib/vunora'

// The CMS page's client rendering boundary. Keeping this file separate from
// the page keeps generateMetadata and the redirect resolver on the server,
// while block rendering happens in the browser bundle — which is what lets
// Vunora's editor live-preview and click-to-edit work on CMS-served slugs.
export default function CmsPageClient(props: { page: VunoraPage | null }) {
  return RenderBlocks({ page: props.page, fallback: null })
}
