/* eslint-disable */
// Generated by Vunora. Do not edit by hand; the import rewrites this file.
// Auto-generated by Vunora site importer. Resolves any slug to a CMS Page
// document and renders its layout. File-based routes for specific slugs in
// this repo continue to win over this catch-all.
import type { Metadata, ResolvingMetadata } from 'next'
import { cookies } from 'next/headers'
import { notFound, permanentRedirect } from 'next/navigation'
import { fetchPage, vunoraJsonLd, vunoraNextMetadata } from '../../lib/vunora'
import CmsPageClient from './cms-page-client'

// Auto-301: look up a renamed slug in Vunora's redirects collection.
// Scoped to THIS site's website id; without one the lookup is skipped
// entirely (an unscoped match could return another site's redirect).
const __VUNORA_API_URL = process.env.NEXT_PUBLIC_VUNORA_API_URL ?? undefined
const __VUNORA_WEBSITE_ID = process.env.NEXT_PUBLIC_VUNORA_WEBSITE_ID ?? "187"
// Site-scoped publishable read key, sent as `x-vunora-key`. Vunora REQUIRES
// it on anonymous reads and derives the scope from it rather than from the
// website id in the query, so a site without a current key resolves no
// redirects until its helper is re-emitted.
const __VUNORA_KEY = process.env.NEXT_PUBLIC_VUNORA_KEY ?? "vnr_pk_4e5e83bc4d0ce54dc23d5ce4761008cf063a617868c5d718"

async function redirectTargetFor(path: string): Promise<string | null> {
  if (!__VUNORA_API_URL || !__VUNORA_WEBSITE_ID) return null
  try {
    const res = await fetch(
      `${__VUNORA_API_URL}/api/redirects?where[from][equals]=${encodeURIComponent(path)}&where[website][equals]=${encodeURIComponent(__VUNORA_WEBSITE_ID)}&depth=1&limit=1`,
      { headers: { Accept: 'application/json', ...(__VUNORA_KEY ? { 'x-vunora-key': __VUNORA_KEY } : {}) } },
    )
    if (!res.ok) return null
    const json = (await res.json()) as {
      docs?: Array<{
        to?: {
          url?: string | null
          reference?: { relationTo?: string; value?: { slug?: string } | string | null } | null
        } | null
      }>
    }
    const to = json.docs?.[0]?.to
    if (!to) return null
    if (to.url) return to.url
    const ref = to.reference
    const value = ref?.value
    const slug = value && typeof value === 'object' ? value.slug : undefined
    if (!slug) return null
    return ref?.relationTo && ref.relationTo !== 'pages'
      ? `/${ref.relationTo}/${slug}`
      : slug === 'home'
        ? '/'
        : `/${slug}`
  } catch {
    return null
  }
}

// Head tags for this slug's CMS document. A slug with no document returns an
// empty object, so this route contributes nothing and the app's own layout
// metadata stands. Next memoizes identical fetches within a request, and the
// helper's fetch carries `next: { revalidate: 60 }` either way, so this does
// not double the upstream reads the page component already makes.
//
// `parent` is not decoration. Next merges this object over the layout's
// SHALLOWLY, so an `openGraph` returned here would REPLACE the layout's —
// dropping og:site_name, og:type, og:locale and its default og:image from
// every CMS page. Awaiting `parent` and building on top of it is the
// supported way to add to the layout's head instead of overwriting it.
//
// The 404 decision lives in the page component below, NOT here: notFound()
// from generateMetadata would 404 preview requests too (metadata resolution
// has the request's searchParams, but throwing here for a missing doc races
// the page's own preview carve-out). A missing doc simply contributes no
// head tags.
export async function generateMetadata(
  props: { params: Promise<{ slug?: string[] }> },
  parent: ResolvingMetadata,
): Promise<Metadata> {
  const params = await props.params
  const slug = (params.slug ?? ['home']).join('/')
  const r = await fetchPage(slug)
  // The helper is framework-neutral by design and types these two groups as
  // plain records rather than importing Next's Metadata, so this is the one
  // place the shapes are reconciled.
  return vunoraNextMetadata(r.data, await parent) as Metadata
}

// Vunora's editor frames this URL to live-preview a draft that has no
// published document yet, and the postMessage carrying that draft can only
// reach a page that mounted. Preview requests therefore keep the empty shell;
// every other visitor takes the notFound() below.
function isVunoraPreviewRequest(
  searchParams: Record<string, string | string[] | undefined>,
): boolean {
  return searchParams['vunora-preview'] === '1' || Boolean(searchParams['vunora-session'])
}

// The author's JSON-LD is rendered HERE and not in generateMetadata, because
// Next's Metadata object has no slot for a script: it serialises titles, metas
// and links only. Next's own structured-data guidance is to render the block
// as an element in the route's component, which is what this does. The string
// is vunoraJsonLd's output, not authored text — JSON.stringify with every <
// replaced by its \u003c escape, so an authored value containing the closing
// script sequence cannot produce one. React would entity-encode a text child,
// and a script element's content is raw text that browsers never decode, so
// dangerouslySetInnerHTML is the mechanism this element requires rather than a
// shortcut around one.
export default async function CmsPage(props: {
  params: Promise<{ slug?: string[] }>
  searchParams: Promise<Record<string, string | string[] | undefined>>
}) {
  const params = await props.params
  const slug = (params.slug ?? ['home']).join('/')
  const visitorId = (await cookies()).get('supercms_visitor_id')?.value
  const r = await fetchPage(slug, undefined, visitorId)
  if (!r.data) {
    const target = await redirectTargetFor('/' + slug)
    if (target) permanentRedirect(target)
    // No document and no rename: this URL does not exist. notFound() is the
    // App Router's own answer for that (HTTP 404 plus this repo's
    // not-found boundary). Rendering on instead served HTTP 200 with an empty
    // body, which a visitor reads as a real but blank page and a crawler
    // indexes as one.
    //
    // Only when the lookup RESOLVED, though. `r.ok === false` means Vunora was
    // unreachable or refused the read, and every slug on the site looks equally
    // pageless in that window, so 404ing them would take the whole site down
    // over one API blip and de-index it. An unresolved lookup keeps the
    // pre-existing shell instead.
    if (r.ok && !isVunoraPreviewRequest(await props.searchParams)) {
      notFound()
    }
  }
  const jsonLd = vunoraJsonLd(r.data ?? null)
  return (
    <>
      {jsonLd ? (
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: jsonLd }} />
      ) : null}
      <CmsPageClient page={r.data ?? null} />
    </>
  )
}
